#pragma once

#define MACROS_STRINGIFY_(VALUE) #VALUE
#define MACROS_STRINGIFY(VALUE) MACROS_STRINGIFY_(VALUE)

#define MACROS_CONCAT_(A, B) A##B
#define MACROS_CONCAT(A, B) MACROS_CONCAT_(A, B)

#define MACROS_UNIQUE_NAME(PREFIX) MACROS_CONCAT(PREFIX_, __COUNTER__)
