#pragma once

#define MACROS_STRINGIFY_INTERNAL(VALUE) #VALUE
#define MACROS_STRINGIFY(VALUE) MACROS_STRINGIFY_INTERNAL(VALUE)

#define MACROS_CONCAT_INTERNAL(A, B) A##B
#define MACROS_CONCAT(A, B) MACROS_CONCAT_INTERNAL(A, B)

#define MACROS_UNIQUE_NAME(PREFIX) MACROS_CONCAT(PREFIX_, __COUNTER__)
