#!/usr/bin/env -S python3 -B
import argparse
import json
import re
import shutil
import subprocess
from pathlib import Path


def prefixed_sections(prefix, phdr=None):
    readelf_path = shutil.which("llvm-readelf")

    if readelf_path is None:
        raise RuntimeError("Could not locate llvm-readelf")

    cmd = [readelf_path, "--sections", "--elf-output-style=JSON", *args.inputs]
    proc = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    if proc.returncode != 0:
        raise RuntimeError(f"Command failed: {' '.join(cmd)}\n{proc.stderr}")

    data = json.loads(proc.stdout)

    prefixed_sections = []

    for file in data:
        file_name = file["FileSummary"]["File"]

        if "Sections" not in file:
            raise RuntimeError(f"JSON parse failed for {file_name}")

        for section_data in file["Sections"]:
            if "Section" not in section_data:
                raise RuntimeError(f"Malformed section in {file_name}")

            section = section_data["Section"]
            name = section["Name"]["Name"]

            if not name.startswith(prefix):
                continue

            if name not in prefixed_sections:
                prefixed_sections.append(name)

    prefixed_sections.sort()

    lines = ["/* Auto-generated prefixed section definitions */"]
    for sec in prefixed_sections:
        lines.append(f"PROVIDE_HIDDEN(ld_{sec}_start = .);")
        lines.append(f"{sec} : {{ *({sec}) }}{' :' + phdr if phdr != None else ''}")
        lines.append(f"PROVIDE_HIDDEN(ld_{sec}_end = .);")
    lines.append("/* End of auto-generated prefixed section definitions */")

    return "\n    ".join(lines)


def required_opt(name):
    value = None
    for opt in args.opt:
        if opt[0] != name:
            continue
        value = opt[1]

    if value == None:
        raise RuntimeError(f"Missing required option: {name}")

    return value


def parse_kv(s: str) -> tuple[str, str]:
    if "=" not in s:
        raise argparse.ArgumentTypeError("expected KEY=VALUE")
    key, value = s.split("=", 1)
    if not key:
        raise argparse.ArgumentTypeError("key must be non-empty")
    return key, value


parser = argparse.ArgumentParser()
parser.add_argument("--template", required=True, help="Template linker file")
parser.add_argument("--dest", required=True, help="Output linker fragment path")
parser.add_argument(
    "--opt",
    action="append",
    default=[],
    type=parse_kv,
    metavar="KEY=VALUE",
    help="Custom option. Repeatable. Example: --opt foo=bar",
)
parser.add_argument("inputs", nargs="+", help="Object files")
args = parser.parse_args()

template_re = re.compile(r"@(.*?)@")

with open(args.template, "r") as template:
    data = "/* Auto-generated by ld-gen.py. DO NOT EDIT. */\n\n" + template.read()

    while True:
        match = template_re.search(data)
        if match == None:
            break

        g = {
            "__builtins__": {
                "prefixed_sections": prefixed_sections,
                "required_opt": required_opt,
            }
        }

        data = data[: match.start()] + eval(match.group(1), g, g) + data[match.end() :]

    dest = Path(args.dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(data, encoding="utf-8")
